// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package test

import (
	"github.com/gin-gonic/gin"
	"template/internal/config"
	"template/internal/handler"
	"template/internal/middleware"
	"template/internal/routes"
)

// Injectors from wire.go:

func InitializeServer() (*gin.Engine, error) {
	pingHandler := handler.NewPingHandler()
	handlers := handler.NewHandlers(pingHandler)
	corsMiddleware := middleware.NewCorsMiddleware()
	middlewares := middleware.NewMiddlewares(corsMiddleware)
	configConfig, err := config.NewConfigTest()
	if err != nil {
		return nil, err
	}
	engine := routes.NewRouter(handlers, middlewares, configConfig)
	return engine, nil
}
